package org.theiet.rsuite.journals.domain.constants;

import com.rsicms.projectshelper.datatype.RSuitePubtrackEvent;

public enum JournalsEvents implements RSuitePubtrackEvent {

    REQUESTED_AUTHOR_COMMENTS, REQUESTED_TYPESETTER_UPDATE, REQUESTED_TYPESETTER_INITIAL,
    REQUESTED_TYPESETTER_FINAL_FILES, AUTHOR_COMMENTS_RECEIVED, 
    TYPESETTER_INITIAL_RECEIVED, ARTICLE_RELEASED, ARTICLE_WITHDRAWN, PUBTRACK_WORKFLOW_STARTED,
    INITIAL_DELIVERY_TO_DIGITAL_LIBRARY,
    DELIVERED_TO_DIGITAL_LIBRARY, INSPEC_CLASSIFICATION_REQUESTED, INSPEC_CLASSIFICATION_RECEIVED, JOURNAL_CODE, TYPESETTER_INITAL_RECEIVED,
    TYPESETTER_UPDATE_RECEIVED, TYPESETTER_FINAL_RECEIVED;
    
    @Override
    public String getEventName() {
        return toString();
    }
}
